//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.PatientDiagnosisHistoryMasters = new HashSet<PatientDiagnosisHistoryMaster>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DentistId { get; set; }
        public string Message { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int Status { get; set; }
    
        public virtual DentistInformation DentistInformation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PatientDiagnosisHistoryMaster> PatientDiagnosisHistoryMasters { get; set; }
    }
}
