//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilStatu
    {
        public CivilStatu()
        {
            this.DentistInformations = new HashSet<DentistInformation>();
            this.PatientInformations = new HashSet<PatientInformation>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<DentistInformation> DentistInformations { get; set; }
        public virtual ICollection<PatientInformation> PatientInformations { get; set; }
    }
}
