//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalDBEntities : DbContext
    {
        public DentalDBEntities()
            : base("name=DentalDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public DbSet<CivilStatu> CivilStatus { get; set; }
        public DbSet<DiagnosisType> DiagnosisTypes { get; set; }
        public DbSet<ImageUrl> ImageUrls { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MouthType> MouthTypes { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<PatientDentalHistory> PatientDentalHistories { get; set; }
        public DbSet<PatientDiagnosisHistoryDetail> PatientDiagnosisHistoryDetails { get; set; }
        public DbSet<PatientDiagnosisHistoryMaster> PatientDiagnosisHistoryMasters { get; set; }
        public DbSet<PatientMedicalHistory> PatientMedicalHistories { get; set; }
        public DbSet<PatientMouth> PatientMouths { get; set; }
        public DbSet<PatientTooth> PatientTeeth { get; set; }
        public DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public DbSet<ScheduleMaster> ScheduleMasters { get; set; }
        public DbSet<Tooth> Teeth { get; set; }
        public DbSet<TreatmentType> TreatmentTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserInformation> UserInformations { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<V_UsersList> V_UsersList { get; set; }
        public DbSet<UserMenu> UserMenus { get; set; }
        public DbSet<DentalMenu> DentalMenus { get; set; }
        public DbSet<V_UserMenu> V_UserMenu { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
    }
}
