//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageUrl
    {
        public ImageUrl()
        {
            this.MouthTypes = new HashSet<MouthType>();
            this.Teeth = new HashSet<Tooth>();
            this.PatientTeeth = new HashSet<PatientTooth>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<MouthType> MouthTypes { get; set; }
        public virtual ICollection<Tooth> Teeth { get; set; }
        public virtual ICollection<PatientTooth> PatientTeeth { get; set; }
    }
}
