//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MouthType
    {
        public MouthType()
        {
            this.PatientMouths = new HashSet<PatientMouth>();
            this.Teeth = new HashSet<Tooth>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageUrlId { get; set; }
        public int Status { get; set; }
    
        public virtual ImageUrl ImageUrl { get; set; }
        public virtual ICollection<PatientMouth> PatientMouths { get; set; }
        public virtual ICollection<Tooth> Teeth { get; set; }
    }
}
