//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnosisHistoryMaster
    {
        public PatientDiagnosisHistoryMaster()
        {
            this.PatientDiagnosisHistoryDetails = new HashSet<PatientDiagnosisHistoryDetail>();
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int AppointmentId { get; set; }
        public decimal Fee { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int Status { get; set; }
        public string Notes { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual ICollection<PatientDiagnosisHistoryDetail> PatientDiagnosisHistoryDetails { get; set; }
        public virtual User User { get; set; }
    }
}
