//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnosisHistoryDetail
    {
        public int Id { get; set; }
        public int PDHMasterId { get; set; }
        public Nullable<int> DiagnosisTypeId { get; set; }
        public Nullable<int> TreatmentTypeId { get; set; }
        public string DiagnosedTeeth { get; set; }
    
        public virtual DiagnosisType DiagnosisType { get; set; }
        public virtual PatientDiagnosisHistoryMaster PatientDiagnosisHistoryMaster { get; set; }
        public virtual TreatmentType TreatmentType { get; set; }
    }
}
