//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalApplicationV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMaster
    {
        public ScheduleMaster()
        {
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int DentistId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual UserInformation UserInformation { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
